services:
  db:
    container_name: ems
    image: postgres:latest
    environment:
      POSTGRES_DB: EmployeeDB
      POSTGRES_USER: eustache
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped

  app:
    build: .
    container_name: employee-management-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/EmployeeDB
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "8082:8080"

    networks:
        - db

networks:
  db:
    driver: bridge
volumes:
  db:
